management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    build:
      enabled: true

logging:
  name: /var/log/sample-boot-application.log
  level:
    sql: INFO
    web: INFO
    io.swagger.models.parameters.AbstractSerializableParameter: error
  #    org.springframework.web: INFO
  #    org.springframework.jdbc.core.JdbcTemplate: INFO
  #    org.springframework.jdbc.core.StatementCreatorUtils: INFO
  #    org.hibernate: INFO
  #    org.hibernate.SQL: INFO
  #    org.hibernate.type.descriptor.sql.BasicBinder: INFO
#  pattern:
#    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
#    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATABASE_URL:jdbc:postgresql://localhost:5432/central-errors}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:codenation}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    database: postgresql
    database-platform: ${SPRING_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    open-in-view: false
    generate-ddl: true
  messages:
    fallback-to-system-locale: true
  data:
    rest:
      defaultMediaType: application/json
    web:
      pageable:
        page-parameter: page
        size-parameter: page-size
        one-indexed-parameters: true
        default-page-size: 10
        max-page-size: 50

server:
  port: 8086
  servlet.contextPath: /
  servlet:
    encoding:
      charset: utf-8
      force: true

app:
  version: 1.0.0
  info:
    title: Central Errors
    name: central-errors
  jwt:
    secret: codenationKey
    expirationTime: 86400000
