management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    build:
      enabled: true

logging:
  name: /var/log/sample-boot-application.log
  level:
    sql: DEBUG
    web: TRACE
    org.springframework.web: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/central-errors
    username: postgres
    password: codenation
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


  messages:
    fallback-to-system-locale: true
  data:
    rest:
      defaultMediaType: application/json

server:
  port: 8086
  servlet.contextPath: /
  servlet:
    encoding:
      charset: utf-8
      force: true

app:
  info:
    title: Central Errors
    name: central-errors
  jwtSecret: codenationKey
  jwtExpirationTime: 86400000
