version: '3.1'
services:
  db:
    container_name: postgres
    image: postgres:12.3
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
#  central-errors:
#    container_name: central-errors
#    build:
#      context: ../
#      args:
#        - "JAR_PATH=/target/errors-central-0.0.1-SNAPSHOT.jar"
#    depends_on:
#      - "db"
#    command: ["./wait-for-it.sh", "db:5432"]
#    ports:
#      - 8085:8085
#    env_file:
#      - env_file.env
#    volumes:
#      - appdata:/usr/src/app/

volumes:
  database-data:
    driver: local
  appdata:
    driver: local